version: '3'

services:
  flight-engine:
    build:
      context: ./Flight-Engine
      dockerfile: ../flightengine.dockerfile
    ports:
      - "3030:3030"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
